id: P006834
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:38.950593
source_metadata:
  id: bdr:W1AC213
  title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་བུདྡྷ་པ་ལི་ཏ།
  author: ''
  volumes:
    e2b85d4409c749da81f68b3632d74dd7:
      image_group_id: I2PD18520
      title: ''
      volume_number: 1
      total_pages: 476
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
