id: I911BB191
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:58:09+00:00'
last_modified: '2022-06-08T07:49:12.214617+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC213
  title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་བུདྡྷ་པ་ལི་ཏ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F40F:
      image_group_id: I2PD18520
      title: ''
      total_pages: 476
      order: 1
      base_file: F40F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
